// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableProxyDirectly() {
  return window['go']['main']['App']['DisableProxyDirectly']();
}

export function DisableProxyViaPowerShell() {
  return window['go']['main']['App']['DisableProxyViaPowerShell']();
}

export function FlushDNSCache() {
  return window['go']['main']['App']['FlushDNSCache']();
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetCurrentLocale() {
  return window['go']['main']['App']['GetCurrentLocale']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function ResetSystemProxy() {
  return window['go']['main']['App']['ResetSystemProxy']();
}

export function ResetTCPIP() {
  return window['go']['main']['App']['ResetTCPIP']();
}

export function ResetWinsock() {
  return window['go']['main']['App']['ResetWinsock']();
}

export function RestartDNSService() {
  return window['go']['main']['App']['RestartDNSService']();
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}
