// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisableProxyDirectly():Promise<string>;

export function DisableProxyViaPowerShell():Promise<string>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetProxyStatus():Promise<main.ProxyStatus>;
