// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisableProxyDirectly():Promise<string>;

export function DisableProxyViaPowerShell():Promise<string>;

export function FlushDNSCache():Promise<string>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetCurrentLocale():Promise<string>;

export function GetProxyStatus():Promise<main.ProxyStatus>;

export function ResetSystemProxy():Promise<string>;

export function ResetTCPIP():Promise<string>;

export function ResetWinsock():Promise<string>;

export function RestartDNSService():Promise<string>;

export function SetLocale(arg1:string):Promise<string>;
